# Meta info for the site
title: Ajai Danial
email: ajaidanial@gmail.com
author: Ajai Danial
description: A go-getter, with crazy passion towards Business, Products & Stock Markets.

# For contact us form
simpleform_url: "https://getsimpleform.com/messages?form_api_token=99de8832756f8b978ef637a1c0add178"

# Other app level config
baseurl: ""
url: ""
domain: ajaidanial.wtf

# Other plugins
plugins:
  - jekyll-gzip
  - jekyll-minifier
